Rewrite `writer-json` using Boost.JSON
csutils/csdiff pull request #105
Opened 2023-01-30 14:10 UTC by lzaoral

TODO: CMake integration is not yet finished.

2023-02-03 16:52 UTC, kdudka requested changes
I like this implementation.  It performs much better in terms of memory consumption than the current implementation.  A few suggestions inline...

2023-02-03 16:52 UTC, kdudka commented on src/lib/writer-json.cc
> +// any type so that no conversions here are needed.
I would not worry too much.  Most of the properties come from `scan.ini`, which is not a type-aware format anyway:
```
[scan]
tool = csmock
tool-version = csmock-3.3.5.20230203.170717.ga8a9617.ini_strip-1.fc36
tool-args = '/usr/bin/csmock' '-r' 'fedora-37-x86_64' '-f' '/home/kdudka/git/csmock/rpm-inst-trash/csmock-3.3.5.20230202.094355.g16818ee.dirty-1.fc36.src.rpm' '-t' 'unicontrol,gitleaks'
host = f36
store-results-to = /home/kdudka/git/csmock/csmock-3.3.5.20230202.094355.g16818ee.dirty-1.fc36.tar.xz
time-created = 2023-02-03 17:07:39
enabled-plugins = gitleaks, unicontrol
mock-config = fedora-37-x86_64
project-name = csmock-3.3.5.20230202.094355.g16818ee.dirty-1.fc36
known-false-positives = /usr/share/csmock/known-false-positives.js
analyzer-version-gitleaks = 8.15.1
analyzer-version-unicontrol = 0.0.2
time-finished = 2023-02-03 17:08:48
exit-code = 0
```

2023-02-03 16:52 UTC, kdudka commented on src/lib/writer-json.cc
> +static void pretty_print(std::ostream &os, const value &jv, std::string* indent = nullptr)
Could you please put encoding of objects and array to separate functions to make the code easier to follow?

The recursive implementation could be a problem if an output format supported by csdiff allowed to control nesting level by the input data.  This is luckily not the case now.  At least I hope so...

2023-02-03 16:52 UTC, kdudka commented on src/lib/writer-json.cc
> -typedef SharedStringPTree PTree;
Thanks to this change, you can also drop the include of `shared-string-ptree.hh` and consequently remove the `shared-string-ptree.hh` header file and the whole `shared-string` module from the project.

2023-02-09 13:02 UTC, lzaoral commented
Newer Boost in EPEL is tracker here: https://bugzilla.redhat.com/show_bug.cgi?id=2165584#

2023-02-09 13:45 UTC, lzaoral commented on src/lib/writer-json.cc
> +static void pretty_print(std::ostream &os, const value &jv, std::string* indent = nullptr)
Addressed in 944abf1.

2023-02-09 13:45 UTC, lzaoral commented on src/lib/writer-json.cc
> -typedef SharedStringPTree PTree;
Addressed in 5706789.

2023-03-02 15:20 UTC, lzaoral commented on src/lib/writer-json.cc
> +// any type so that no conversions here are needed.
Thanks for the explanation!

2023-03-03 08:16 UTC, kdudka commented on tests/CMakeLists.txt
> +set(jsfilter "sed -e 's|\"version\": \"[^\"]*\"|\"version\": \"\"|g'")
I guess we can remove these filters also from `tests/test-lib.sh`?

2023-03-03 08:30 UTC, lzaoral commented on tests/CMakeLists.txt
> +set(jsfilter "sed -e 's|\"version\": \"[^\"]*\"|\"version\": \"\"|g'")
Sure, addressed in 30964cd.

2023-03-03 11:14 UTC, kdudka approved these changes
Thanks for the update!  I think we can merge this...

2023-03-03 11:28 UTC, lzaoral commented
Thank you, @kdudka! Merging.

2023-03-03 11:29 UTC, merged