Json writer: use separate compilation units for each JSON scheme
csutils/csdiff pull request #115
Opened 2023-03-04 11:44 UTC by kdudka

2023-03-04 16:51 UTC, lzaoral requested changes
LGTM apart from the `using namespace` in a header!  Details inline.

2023-03-04 16:51 UTC, lzaoral commented on src/lib/writer-json-common.cc
> +    boost::json::object scan;
Previous line defines `using namespace boost::json;` so we can use:
```suggestion
object jsonSerializeScanProps(const TScanProps &scanProps)
{
    static auto isDigit = [](unsigned char c){ return std::isdigit(c); };

    object scan;
```

2023-03-04 16:51 UTC, lzaoral commented on src/lib/writer-json-sarif.hh
> +};
I don't think it's a good idea to flatten a namespace in a header file.  The using declaration should be moved to `src/lib/writer-json-sarif.cc` instead.

2023-03-04 20:44 UTC, kdudka commented on src/lib/writer-json-common.cc
> +    boost::json::object scan;
Fixed in commit 184c906270a36e8c823cdc4d1f551d8dfd676170.

2023-03-04 20:45 UTC, kdudka commented on src/lib/writer-json-sarif.hh
> +};
Right.  It was a copy-paste mistake.  Thank you for spotting it!

2023-03-04 20:46 UTC, kdudka commented on src/lib/writer-json-sarif.hh
> +};
Fixed in commit 71c1aee21c380e3b647ebfba5d94802a80de2247.

2023-03-05 13:31 UTC, lzaoral approved these changes
LGTM, thanks @kdudka!  Minor nits I missed yesterday are inline.

2023-03-05 13:31 UTC, lzaoral commented on src/lib/writer-json-common.cc
> +
Redundant empty line. Sorry for introducing it in #105.

2023-03-05 13:31 UTC, lzaoral commented on src/lib/writer-json-common.cc
> +        std::string                *indent)
```suggestion
        std::ostream               &os,
        const value                &jv,
        std::string                *indent)
```

2023-03-05 14:20 UTC, kdudka commented on src/lib/writer-json-common.cc
> +
Fixed in commit c436c719f89e7f071c423c5e658a42b6b48a6801.

2023-03-05 14:20 UTC, kdudka commented on src/lib/writer-json-common.cc
> +        std::string                *indent)
Fixed in commit c436c719f89e7f071c423c5e658a42b6b48a6801.

2023-03-05 14:21 UTC, kdudka commented
@lzaoral Thanks for review!  Merging...

2023-03-05 14:21 UTC, merged