parser-gcc: implement parsing of UBSAN reports
csutils/csdiff pull request #129
Opened 2023-05-29 14:32 UTC by lzaoral

Resolves: https://github.com/csutils/csdiff/issues/108

2023-05-29 15:51 UTC, kdudka requested changes
Thank you for working on this!  Although the line diff looks small, the single commit combines multiple more or less independent changes.  I would split it into 3 smaller commits:
- change the way how we refer to sub-expressions in regular expressions (no change in behavior)
- make the GCC parser silently ignore empty lines (change in behavior not specific to UBSAN)
- finally the changes specific to the UBSAN data format

2023-05-29 15:51 UTC, kdudka commented on src/lib/parser-gcc.cc
> +        pEvt->msg   = sm[/* fnc */ 2] + " at " + sm[/* address */ 1];
Should we add the `()` suffix after `fnc`, as we do for smatch?

2023-05-29 15:51 UTC, kdudka commented on src/lib/parser-gcc.cc
> +            && pDef->checker != "UBSAN_WARNING")
It is not obvious why we need to special-case `UBSAN_WARNING` here.  Could we please cover it by a test-case?

2023-05-29 15:51 UTC, kdudka commented on src/lib/parser-gcc.cc
> +    else if (keyEvt.event == "runtime error")
Is `runtime error` sufficiently specific to `UBSAN_WARNING`?  Do we have a plan for future extensions?  We should probably clarify it in a comment.

2023-05-30 07:41 UTC, lzaoral commented on src/lib/parser-gcc.cc
> +            && pDef->checker != "UBSAN_WARNING")
I'll add a comment explaining it.  The line is already covered by a test, without this change, the `note` events would not be merged with the `runtime error` key event.

2023-05-30 08:14 UTC, lzaoral commented on src/lib/parser-gcc.cc
> +        pEvt->msg   = sm[/* fnc */ 2] + " at " + sm[/* address */ 1];
Good idea!  Addressed in 484354606f7b4fe877235831f7cd1c5e7e82a5da.

2023-05-30 08:15 UTC, lzaoral commented on src/lib/parser-gcc.cc
> +    else if (keyEvt.event == "runtime error")
Comment added in 484354606f7b4fe877235831f7cd1c5e7e82a5da.

2023-05-30 08:15 UTC, lzaoral commented on src/lib/parser-gcc.cc
> +            && pDef->checker != "UBSAN_WARNING")
Comment added in 484354606f7b4fe877235831f7cd1c5e7e82a5da.

2023-05-30 16:23 UTC, kdudka commented on src/lib/parser-gcc.cc
> +            && pDef->checker != "UBSAN_WARNING")
This was indeed covered by a test but the test was not included in the cmake list when I was doing the review, so the test-suite was passing by mistake for me.  I think a saner solution would be to move the matching of `UBSAN_WARNING` to `GccPostProcessor` so that we do not need to special-case `UBSAN_WARNING` in the defect merging loop.  I have proposed the solution in commit 8a5fcb94fa5e76141f1c25bb7c46f371537b925a.

2023-05-31 11:33 UTC, kdudka approved these changes
Looks good.  Thanks for the contribution!

2023-05-31 11:42 UTC, merged