parser-gcc: fix incomplete file paths in UBSAN key events
csutils/csdiff pull request #130
Opened 2023-05-31 16:26 UTC by lzaoral

UBSAN may only use the base name for the file path in its key event. However, the top of the backtrace, if present, always contains the whole path to this file.

This fixes `csmock` throwing all UBSAN warnings into the suppressed category.

2023-05-31 16:29 UTC, lzaoral commented on src/lib/parser-gcc.cc
> +
Addressed in c2c1ae32447d01edb93c5e9c48bddc186785b692.

2023-06-04 20:30 UTC, kdudka commented on src/lib/parser-gcc.cc
> +            keyEvt.fileName = evt.fileName;
Should we check that the line numbers (and maybe basenames?) match for the pair of events so that we do not combine file name and position from two different locations (e.g. when function inlining is involved)?

2023-09-12 11:55 UTC, lzaoral commented on src/lib/parser-gcc.cc
> +            keyEvt.fileName = evt.fileName;
Addressed in 4bf72145084eaaae77e5d8301bb615b4e0b26e27.  Sorry for such a late response!

2023-09-12 13:13 UTC, kdudka requested changes

2023-09-12 13:13 UTC, kdudka commented on src/lib/parser-gcc.cc
> +                && path(keyEvt.fileName).filename() == path(keyEvt.fileName).filename()
The expression `path(keyEvt.fileName).filename() == path(keyEvt.fileName).filename()` will always be true.  I think this should be written in a more readable way.

2023-09-12 15:23 UTC, kdudka approved these changes

2023-09-12 15:23 UTC, kdudka commented on src/lib/parser-gcc.cc
> +        const auto &keyFileName = path(keyEvt.fileName).filename();
I would move this assignment before the `for` loop.

2023-09-12 15:23 UTC, kdudka commented on src/lib/parser-gcc.cc
> +                && keyEvt.line == evt.line) {
I would put a newline between `)` and `{`.

2023-09-13 08:30 UTC, lzaoral commented on src/lib/parser-gcc.cc
> +                && keyEvt.line == evt.line) {
Addressed in  be20b75d9e60afe8bb3820d668750fceadd3907b.

2023-09-13 10:40 UTC, merged