propagate endLine/endColumn
csutils/csdiff pull request #167
Opened 2024-03-29 12:36 UTC by kdudka

Initially csdiff supported only `startLine`/`startColumn`.  Some scanners provide also `endLine`/`endColumn` to denote a region of certain size.

The extra information is stored efficiently in the internal data structure and in csdiff's native JSON format by tracking the diff between `startLine`/`endLine` and `startColumn`/`endColumn`, respectively, and only when the diff is a non-zero (positive) number.

Resolves: https://github.com/csutils/csdiff/issues/136

2024-04-03 08:37 UTC, jamacku reviewed
Thank you for working on this RFE. I have tried to test it, and unfortunately, the `endLine`/`endColumn` properties aren't filled for the following shell script.

```
[root@vm-10-0-187-125 ~]# cat main.sh 
# shell.sh
echo $1                           # Unquoted variables
find . -name *.ogg                # Unquoted find/grep patterns
rm "~/my file.txt"                # Quoted tilde expansion
v='--verbose="true"'; cmd $v      # Literal quotes in variables
for f in "*.ogg"                  # Incorrectly quoted 'for' loops
touch $@                          # Unquoted $@

[root@vm-10-0-187-125 ~]# shellcheck --format=json1 main.sh | csgrep --mode=sarif  | sarif-fmt
error: Couldn't parse this for loop. Fix to allow more checks.
  ┌─ main.sh:6:1
  │
6 │ for f in "*.ogg"                  # Incorrectly quoted 'for' loops
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Expected 'do'.
  ┌─ main.sh:7:1
  │
7 │ touch $@                          # Unquoted $@
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Expected 'do'. Fix any mentioned problems and try again.
  ┌─ main.sh:7:1
  │
7 │ touch $@                          # Unquoted $@
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: 0 errors emitted

[root@vm-10-0-187-125 ~]# shellcheck --format=json main.sh | shellcheck-sarif  | sarif-fmt
error: Couldn't parse this for loop. Fix to allow more checks.
  ┌─ main.sh:6:1
  │
6 │ for f in "*.ogg"                  # Incorrectly quoted 'for' loops
  │ ^
  │
  = SC1073
  = For more information: https://www.shellcheck.net/wiki/SC1073

error: Expected 'do'.
  ┌─ main.sh:7:1
  │
7 │ touch $@                          # Unquoted $@
  │ ^
  │
  = SC1058
  = For more information: https://www.shellcheck.net/wiki/SC1058

error: Expected 'do'. Fix any mentioned problems and try again.
  ┌─ main.sh:7:1
  │
7 │ touch $@                          # Unquoted $@
  │ ^
  │
  = SC1072
  = For more information: https://www.shellcheck.net/wiki/SC1072

error: 0 errors emitted
```

But when I commented last two lines, so ShellCheck could parse the whole file, the properties are set correctly by `csgrep`

```
[root@vm-10-0-187-125 ~]# cat main.sh 
# shell.sh
echo $1                           # Unquoted variables
find . -name *.ogg                # Unquoted find/grep patterns
rm "~/my file.txt"                # Quoted tilde expansion
v='--verbose="true"'; cmd $v      # Literal quotes in variables
#for f in "*.ogg"                  # Incorrectly quoted 'for' loops
#touch $@                          # Unquoted $@

shellcheck --format=json1 main.sh | csgrep --mode=sarif  | sarif-fmt
error: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
  ┌─ main.sh:1:1
  │
1 │ # shell.sh
  │ ^^^^^^^^^^

warning: Double quote to prevent globbing and word splitting.
  ┌─ main.sh:2:6
  │
2 │ echo $1                           # Unquoted variables
  │      ^^

warning: Quote the parameter to -name so the shell won't interpret it.
  ┌─ main.sh:3:14
  │
3 │ find . -name *.ogg                # Unquoted find/grep patterns
  │              ^^^^^

warning: Use ./*glob* or -- *glob* so names with dashes won't become options.
  ┌─ main.sh:3:14
  │
3 │ find . -name *.ogg                # Unquoted find/grep patterns
  │              ^

warning: Tilde does not expand in quotes. Use $HOME.
  ┌─ main.sh:4:5
  │
4 │ rm "~/my file.txt"                # Quoted tilde expansion
  │     ^^^^^^^^^^^^^

warning: Quotes/backslashes will be treated literally. Use an array.
  ┌─ main.sh:5:3
  │
5 │ v='--verbose="true"'; cmd $v      # Literal quotes in variables
  │   ^^^^^^^^^^^^^^^^^^

warning: Quotes/backslashes in this variable will not be respected.
  ┌─ main.sh:5:27
  │
5 │ v='--verbose="true"'; cmd $v      # Literal quotes in variables
  │                           ^^

warning: 6 warnings emitted
error: 6 errors emitted
```

2024-04-03 08:50 UTC, lzaoral requested changes

2024-04-03 08:50 UTC, lzaoral commented on src/lib/defect.hh
> +    short               vSize           = 0; //< endLine - startLine
I'd probably use `unsigned short`, because `diffNums` already makes sure that the stored value is not negative.

2024-04-03 08:50 UTC, lzaoral commented on src/lib/defect.hh
> +        : 0;
OT: When we switch to C++17, we can repalce this with `std::clamp`: https://en.cppreference.com/w/cpp/algorithm/clamp

2024-04-03 08:50 UTC, lzaoral commented on src/lib/parser-json-gcc.cc
> +    // read file name
Maybe add `using std::string` for consistency with the functions below?

2024-04-03 08:50 UTC, lzaoral commented on src/lib/parser-json-gcc.cc
> +            && gccReadLocRegion(pEvt, *beg, *end))
Nit:  I'd use different names for the pointers because the first thing that came to my mind I saw `*end` was:
> Why is there a deference of end iterator?

(The same remark applies also to the function above.)

2024-04-03 08:50 UTC, lzaoral commented on src/lib/parser-json-gcc.cc
> +    if ((pEvt->column = valueOf<int>(beg, "byte-column"))) {
Is it possible that GCC will generate report that will have `0` for the start line and some positive value for the finish line?  (The same goes for columns.)

2024-04-03 08:50 UTC, lzaoral commented on src/lib/parser-json-gcc.cc
> +    if ((pEvt->column = valueOf<int>(beg, "byte-column"))) {
And the same also goes for different input formats.

2024-04-03 08:50 UTC, lzaoral commented on src/lib/parser-json-simple.cc
> +        evt.vSize       = valueOf<short         >(evtNode, "v_size");
Do not forget to update these as well, if you change the type to `unsigned short`.

2024-04-03 08:50 UTC, lzaoral commented on tests/csgrep/0094-gcc-json-stdout.txt
> +                    "h_size": 7,
This is suspicious.  Other updated test outputs did not change existing fields.

2024-04-03 08:50 UTC, lzaoral commented on tests/csgrep/0094-gcc-json-stdout.txt
> +                    "h_size": 11,
Ditto.

2024-04-03 10:59 UTC, kdudka commented
@jamacku Thank you for testing it!  The problem you pointed out should be fixed in b67c44fbc8cbbf180f051105bf341c814fb3102a.

2024-04-03 11:21 UTC, kdudka commented on src/lib/defect.hh
> +    short               vSize           = 0; //< endLine - startLine
The idea was to avoid mixing signed/unsigned types while adding them to `line` and `column`, which are signed.  On the other hand `usigned short` allows us to propagate one more bit.  I have also created the `TNumDiff` type name so that this is easier to change later on.  Committed as 10afff8d6350174311c1e79555aea9143ff9c88a.

2024-04-03 11:24 UTC, kdudka commented on src/lib/defect.hh
> +        : 0;
`std::clamp` with return `USHORT_MAX` for numbers above the limit whereas `diffNums()` returns 0 in this case, which means the value is dropped.

2024-04-03 11:32 UTC, kdudka commented on src/lib/parser-json-gcc.cc
> +    // read file name
I have moved it to the global level (after includes) to simplify it.  Fixed in e886689876a46b9d682b10c8d9fe6f4de44ab770.

2024-04-03 11:32 UTC, kdudka commented on src/lib/parser-json-gcc.cc
> +            && gccReadLocRegion(pEvt, *beg, *end))
Renamed to `start` and `finish` in e886689876a46b9d682b10c8d9fe6f4de44ab770.

2024-04-03 11:35 UTC, kdudka commented on src/lib/parser-json-gcc.cc
> +    if ((pEvt->column = valueOf<int>(beg, "byte-column"))) {
All the tools I know number lines starting with 1.  If line number is 0, it means that line number is not available for the finding.  In that case, there is no region to size with `h_size`/`v_size`.

2024-04-03 11:36 UTC, kdudka commented on src/lib/parser-json-simple.cc
> +        evt.vSize       = valueOf<short         >(evtNode, "v_size");
Fixed in 10afff8d.

2024-04-03 11:43 UTC, jamacku reviewed
Works great, Thank you

```
[root@vm-10-0-187-125 ~]# shellcheck --format=json1 main.sh | csgrep --mode=sarif  | sarif-fmt
error: Couldn't parse this for loop. Fix to allow more checks.
  ┌─ main.sh:6:1
  │
6 │ for f in "*.ogg"                  # Incorrectly quoted 'for' loops
  │ ^

error: Expected 'do'.
  ┌─ main.sh:7:1
  │
7 │ touch $@                          # Unquoted $@
  │ ^

error: Expected 'do'. Fix any mentioned problems and try again.
  ┌─ main.sh:7:1
  │
7 │ touch $@                          # Unquoted $@
  │ ^

error: 0 errors emitted
```
```
[root@vm-10-0-187-125 ~]# shellcheck --format=json1 main.sh | csgrep --mode=sarif  | sarif-fmt
error: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
  ┌─ main.sh:1:1
  │
1 │ # shell.sh
  │ ^

warning: Double quote to prevent globbing and word splitting.
  ┌─ main.sh:2:6
  │
2 │ echo $1                           # Unquoted variables
  │      ^^

warning: Quote the parameter to -name so the shell won't interpret it.
  ┌─ main.sh:3:14
  │
3 │ find . -name *.ogg                # Unquoted find/grep patterns
  │              ^^^^^

warning: Use ./*glob* or -- *glob* so names with dashes won't become options.
  ┌─ main.sh:3:14
  │
3 │ find . -name *.ogg                # Unquoted find/grep patterns
  │              ^

warning: Tilde does not expand in quotes. Use $HOME.
  ┌─ main.sh:4:5
  │
4 │ rm "~/my file.txt"                # Quoted tilde expansion
  │     ^^^^^^^^^^^^^

warning: Quotes/backslashes will be treated literally. Use an array.
  ┌─ main.sh:5:3
  │
5 │ v='--verbose="true"'; cmd $v      # Literal quotes in variables
  │   ^^^^^^^^^^^^^^^^^^

warning: Quotes/backslashes in this variable will not be respected.
  ┌─ main.sh:5:27
  │
5 │ v='--verbose="true"'; cmd $v      # Literal quotes in variables
  │                           ^^

warning: 6 warnings emitted
error: 6 errors emitted
```

2024-04-03 11:44 UTC, kdudka commented on tests/csgrep/0094-gcc-json-stdout.txt
> +                    "h_size": 7,
The native JSON output of GCC is too rich for `csdiff` to handle it (and obsoleted by GCC's SARIF output already).  It provides up to three pairs of line/column:

- `start`
- `finish`
- `caret` (may point somewhere between `start` and `finish`)

The initial implementation of `GccTreeDecoder` completely ignored `start` a `finish` because `caret` was the only object that was available in all events (except events that had no location info at all).

This pull request changes `GccTreeDecoder` to use `start`/`finish` in a way that is compatible with SARIF's region object if both `start` and `finish` are available.  If any of them is missing (you can find examples in csdiff's test-suite), there is a fallback to `caret`.

Does it make sense?

2024-04-03 11:44 UTC, kdudka commented on tests/csgrep/0094-gcc-json-stdout.txt
> +                    "h_size": 11,
Ditto.

2024-04-03 11:45 UTC, lzaoral commented on tests/csgrep/0094-gcc-json-stdout.txt
> +                    "h_size": 7,
Yes, it makes perfect sense.  Thank you for the explanation, @kdudka!

2024-04-03 11:56 UTC, kdudka commented
@jamacku Perfect.  Thank you for testing it!

2024-04-09 10:10 UTC, lzaoral commented on tests/csgrep/0090-sarif-writer-illegal-utf8-sequence-stdout.txt
> +                                    "endLine": 0
nit: The input file is an artificial test created in 620dc470d46908c64d3a5d14c78e015c71836aee which does not include line information at all.  Shall we fix that?

2024-04-09 10:12 UTC, lzaoral commented on tests/csgrep/0094-gcc-json-stdout.txt
> +                    "h_size": 7,
Oh, now I get it why it is called `caret`:
```
test.c: In function ‘main’:
test.c:4:13: warning: ‘a’ is used uninitialized [-Wuninitialized]
    4 |     return a[0];
      |            ~^~~
```
It is the location of the literal `^` caret character in the diagnostic and `start` and `finish` seem to correspond to the boundaries of the `~` squiggly line.

2024-04-09 10:19 UTC, lzaoral commented
@jamacku This is probably unrelated to this PR but the first output from `sarif-fmt` in https://github.com/csutils/csdiff/pull/167#pullrequestreview-1976532916 is weird.  There three errors but the summary shows:
```
error: 0 errors emitted
```

2024-04-09 10:19 UTC, jamacku commented on tests/csgrep/0090-sarif-writer-illegal-utf8-sequence-stdout.txt
> +                                    "endLine": 0
It might be good to have such data for test purposes.

2024-04-09 10:25 UTC, jamacku commented
> @jamacku This is probably unrelated to this PR but the first output from `sarif-fmt` in [#167 (review)](https://github.com/csutils/csdiff/pull/167#pullrequestreview-1976532916) is weird. There three errors but the summary shows:
> 
> ```
> error: 0 errors emitted
> ```

TBH, I'm not sure what those values should represent. It is possible that values might be a bit misleading. For example the second report shows number of errors 6 but there is 7 reports.

2024-04-09 10:25 UTC, lzaoral approved these changes
Approving.  The comments above are either minor remarks or questions.

2024-04-09 10:26 UTC, jamacku approved these changes
LGTM, works with `sarif-fmt`

2024-04-09 13:20 UTC, kdudka commented on tests/csgrep/0090-sarif-writer-illegal-utf8-sequence-stdout.txt
> +                                    "endLine": 0
According to https://sarifweb.azurewebsites.net/Validation the zeroes trigger validation errors.  I will replace them with 1.

2024-04-09 13:26 UTC, kdudka commented on tests/csgrep/0090-sarif-writer-illegal-utf8-sequence-stdout.txt
> +                                    "endLine": 0
Nope.  This is not a test input but invalid output of csdiff's SARIF writer.  The correct fix is to not write the `region` object in case we have no line numbers.

2024-04-09 13:50 UTC, kdudka commented on tests/csgrep/0090-sarif-writer-illegal-utf8-sequence-stdout.txt
> +                                    "endLine": 0
Fixed in 1d29439addac86d5fe0265f2c6405e69f29d23ad.

2024-04-09 14:10 UTC, merged