sarif: initial implementation of csdiff fingerprints
csutils/csdiff pull request #168
Opened 2024-03-29 21:00 UTC by kdudka

# csdiff/v0 fingerprints

It hashes the data that csdiff uses in its matching algorithm.
The interfaces are already prepared for csdiff/v1, which will
also take the line content into account when available.

From the updated tests it is obvious that these hashes already
have numerous collisions on the existing test data.

# csdiff/v1 fingerprints
    
It hashes the data that csdiff uses in its matching algorithm
and the line content without spaces.  For this fingerprint to
be computed, the results need to include the line content for 
the key event in the format produced by `csgrep --embed-context`.

Related: https://issues.redhat.com/browse/OSH-9
Resolves: https://github.com/csutils/csdiff/issues/98

2024-04-26 04:43 UTC, jamacku commented
Great example when codeql fingerprints work:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/376

```sh
✋ Defects, NEEDS INSPECTION
Error: SHELLCHECK_WARNING:
./src/functions.sh:309:46: warning[SC2154]: GITHUB_REF is referenced but not assigned.
#  306|   uploadSARIF () {
#  307|     is_debug && local verbose=--verbose
#  308|   
#  309|->   echo '{"commit_oid":"'"${HEAD}"'","ref":"'"${GITHUB_REF//merge/head}"'","analysis_key":"differential-shellcheck","sarif":"'"$(gzip -c output.sarif | base64 -w0)"'","tool_names":["differential-shellcheck"]}' > payload.json
#  310|   
#  311|     local curl_args=(
#  312|       "${verbose:---silent}"

Error: SHELLCHECK_WARNING:
./src/functions.sh:331:24: info[SC2312]: Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).
#  328|   
#  329|   get_shellcheck_version () {
#  330|     local shellcheck_version
#  331|->   shellcheck_version=$(shellcheck --version | grep -w "version:" | cut -s -d ' ' -f 2)
#  332|   
#  333|     echo "${shellcheck_version}"
#  334|   }

Error: SHELLCHECK_WARNING:
./src/functions.sh:331:47: info[SC2312]: Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).
#  328|   
#  329|   get_shellcheck_version () {
#  330|     local shellcheck_version
#  331|->   shellcheck_version=$(shellcheck --version | grep -w "version:" | cut -s -d ' ' -f 2)
#  332|   
#  333|     echo "${shellcheck_version}"
#  334|   }
```

[The code hasn't changed](https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/376/files) for the last two defects, but they were still reported by csdiff.

I'll try to check if csdiff fingerprints would give the same results as codeql.

2024-04-26 15:14 UTC, jamacku commented
Here is the `csgrep` output from before the change and after:

- [before.json](https://github.com/csutils/csdiff/files/15132319/before.json)
- [after.json](https://github.com/csutils/csdiff/files/15132318/after.json)

You should be able to reproduce the above situation form:

- https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/376

2024-04-26 15:52 UTC, kdudka commented
@jamacku Nice!  I have added it as a regression test in 95e35d316e0ed968e59d8687fddc607692fd7b47.  It passes with ca7f32a5e1ed45b7e86da091fa6a2efe7f762b29 but not without it.

2024-04-26 16:24 UTC, jamacku approved these changes
Thank you @kdudka

2024-05-02 08:54 UTC, lzaoral requested changes

2024-05-02 08:54 UTC, lzaoral commented on src/csgrep.cc
> +        && chainDecoratorGeneric<FingerPrintFilter>(pEng, vm, "hash-v1");
nit: sort and align?
```suggestion
    return chainDecoratorGeneric<FingerPrintFilter>(pEng, vm, "hash-v1")
        && chainDecoratorIntArg <ImpLevelFilter>   (pEng, vm, "imp-level");
```

2024-05-02 08:54 UTC, lzaoral commented on src/lib/finger-print.cc
> +static const std::string sep = "\n";
```suggestion
static constexpr std::string sep = "\n";
```

2024-05-02 08:54 UTC, lzaoral commented on src/lib/finger-print.cc
> +static std::string computeHexSHA1(const std::string &str)
```suggestion
static inline std::string computeHexSHA1(const std::string &str)
```

2024-05-02 08:54 UTC, lzaoral commented on src/lib/finger-print.cc
> +std::string FingerPrinter::getLineContent() const
```suggestion
inline std::string FingerPrinter::getLineContent() const
```

(If the function dodo not depend on the `Private` type, I'd have suggested to just implement this method directly in the header file.)

2024-05-02 14:52 UTC, kdudka commented on src/lib/finger-print.cc
> +static const std::string sep = "\n";
This fails to compile:
```
finger-print.cc:89:30: error: the type ‘const std::string’ {aka ‘const std::__cxx11::basic_string<char>’} of ‘constexpr’ variable ‘sep’ is not literal
   89 | static constexpr std::string sep = "\n";
      |                              ^~~
In file included from /usr/include/c++/13/string:54,
                 from /home/kdudka/git/csdiff/src/lib/defect.hh:25,
                 from /home/kdudka/git/csdiff/src/lib/finger-print.hh:23,
                 from /home/kdudka/git/csdiff/src/lib/finger-print.cc:20:
/usr/include/c++/13/bits/basic_string.h:87:11: note: ‘std::__cxx11::basic_string<char>’ is not literal because:
   87 |     class basic_string
      |           ^~~~~~~~~~~~
/usr/include/c++/13/bits/basic_string.h:87:11: note:   ‘std::__cxx11::basic_string<char>’ has a non-trivial destructor
```

2024-05-02 14:55 UTC, lzaoral commented on src/lib/finger-print.cc
> +static const std::string sep = "\n";
Oh, right...  I forgot that `std::string` is not `constexpr` in pure C++11.  Sorry.

2024-05-02 14:56 UTC, kdudka commented on src/lib/finger-print.cc
> +std::string FingerPrinter::getLineContent() const
This breaks the linking:
```
[ 72%] Linking CXX executable csdiff
/usr/bin/ld: lib/libcs.a(deflookup.cc.o): in function `DefLookup::lookup(Defect const&)':
/home/kdudka/git/csdiff/src/lib/deflookup.cc:86: undefined reference to `FingerPrinter::getLineContent[abi:cxx11]() const'
/usr/bin/ld: lib/libcs.a(deflookup.cc.o): in function `defLookupCore':
/home/kdudka/git/csdiff/src/lib/deflookup.cc:91: undefined reference to `FingerPrinter::getLineContent[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
```

2024-05-02 15:16 UTC, kdudka commented on src/csgrep.cc
> +        FingerPrintFilter(AbstractWriter *agent, const std::string hashPrefix):
Fixed in 83f4b2f18e15ae302d06d415097ed75ad2e41184.

2024-05-02 15:16 UTC, kdudka commented on src/csgrep.cc
> +        && chainDecoratorGeneric<FingerPrintFilter>(pEng, vm, "hash-v1");
Fixed in 83f4b2f18e15ae302d06d415097ed75ad2e41184.

2024-05-02 15:17 UTC, kdudka commented on src/lib/finger-print.hh
> +    FPV_MAX
`FPV_MAX` should always be the last item.  I have added a comment in 6e6549dd266d0fe9a4c86778252f76ee267cefb5 to make it clear.

2024-05-02 15:18 UTC, kdudka commented on src/lib/hash-util.hh
> +    // FIXME: std::remove_reference is needed on el7 (boost-1.53)
True.  I have added a separate [commit](6e6549dd266d0fe9a4c86778252f76ee267cefb5) to drop the compatibility in case it was needed later on elsewhere.

2024-05-02 15:18 UTC, kdudka commented on src/lib/writer-json-sarif.cc
> +        fps[label] = std::move(fingerPrint);
Fixed in 6e6549dd266d0fe9a4c86778252f76ee267cefb5.

2024-05-02 16:36 UTC, lzaoral commented
Somehow, the comment I've just written is not here. Reposting:

2024-05-02 16:46 UTC, lzaoral commented on src/lib/writer-json-sarif.cc
> +        fps.emplace(std::move(label), std::move(fingerPrint));
@kdudka Alright, in the current state (or the previous one), using `std::move` is useless. I did not realise that both strings are `const` and `std::string` has no constructors which accept a `const` r-value reference (`const std::string &&`).

2024-05-02 16:51 UTC, lzaoral approved these changes
It's up to you if you want to use a move or copy constructor for the elements of the map.  Otherwise, LGTM.

2024-05-03 10:53 UTC, kdudka commented on src/lib/writer-json-sarif.cc
> +        fps.emplace(std::move(label), std::move(fingerPrint));
Thank you for clarifying it!  I have dropped 0267593b304b7b2e2a23ddb84b0c2af5a263719b to make the code easier to read.

2024-05-03 11:33 UTC, kdudka commented
@jamacku @lzaoral Thank you both for review!

2024-05-03 11:33 UTC, merged