`csgrep --mode=sarif`: use SARIF output format
csutils/csdiff pull request #39
Opened 2022-04-01 15:51 UTC by kdudka

This is a work in progress.  The actual writer is not yet implemented.

2022-04-07 15:16 UTC, kdudka commented
The code slowly starts to work and does not obviously break anything that originally worked.  So I would prefer to merge it as it is and continue with further tweaks of the encoder/decoder in separate pull requests.  @lzaoral What do you think about this approach?  It would help to avoid unnecessary conflicts with the other changes you are working on.

2022-04-12 09:46 UTC, lzaoral requested changes

2022-04-12 09:46 UTC, lzaoral commented on src/json-writer.cc
> +        virtual void writeTo(std::ostream &);
```suggestion
        void importScanProps(const TScanProps &) override;

        /// append single defect
        void appendDef(const Defect &) override;

        /// write everything to the given output stream
        void writeTo(std::ostream &) override;
```

2022-04-12 12:29 UTC, kdudka commented on src/abstract-tree.hh
> +    pDst->push_back(std::make_pair("", src));
It does not seem to work with `boost::property_tree`:
```
In file included from /home/kdudka/git/csdiff/src/json-writer.cc:22:
/home/kdudka/git/csdiff/src/abstract-tree.hh: In instantiation of ‘void appendNode(TNode*, const TNode&) [with TNode = boost::property_tree::basic_ptree<std::__cxx11::basic_string<char>, SharedStr>]’:
/home/kdudka/git/csdiff/src/json-writer.cc:84:19:   required from here
/home/kdudka/git/csdiff/src/abstract-tree.hh:76:11: error: ‘class boost::property_tree::basic_ptree<std::__cxx11::basic_string<char>, SharedStr>’ has no member named ‘emplace_back’
   76 |     pDst->emplace_back("", src);
      |     ~~~~~~^~~~~~~~~~~~
```

2022-04-12 12:54 UTC, kdudka commented
Thanks for review!  I have updated the pull request to reflect the review comments.

2022-04-12 13:20 UTC, lzaoral commented on src/abstract-tree.hh
> +    pDst->push_back(std::make_pair("", src));
Oh, my apologies. When I saw `push_back`, I immediately though that it's some container derived from `std::deque`. (In that case, `emplace_back` would have been better.)

2022-04-12 13:36 UTC, lzaoral requested changes
Thanks a lot, @kdudka!  I think the PR is ready to be merged after the two remaining comments are addressed.

2022-04-12 13:36 UTC, lzaoral commented on src/json-writer.hh
>          virtual void setScanProps(const TScanProps &);
These should be converted to use `override` as well. Otherwise, `clang` with `-Wall` issues a `-Winconsistent-missing-override` warning when some (but not all!) overridden methods use the `override` identifier.

2022-04-13 07:22 UTC, kdudka commented
Thanks for review!  Ale review comments should be addressed and fix-up commits squashed.

2022-04-13 10:43 UTC, lzaoral approved these changes
LGTM! Thanks, @kdudka!

2022-04-13 11:55 UTC, closed without merging