WIP: Port the project to C++11
csutils/csdiff pull request #40
Opened 2022-04-13 15:04 UTC by lzaoral

This WIP at the moment.

2022-04-20 07:43 UTC, kdudka commented on src/abstract-parser.hh
> +        const TScanProps emptyProps_{};
Just curious, why do we need the extra brackets?

2022-04-20 08:03 UTC, lzaoral commented on src/abstract-parser.hh
> +        const TScanProps emptyProps_{};
Defaulted constructors do not initialize non-`static` and `const` members. From https://en.cppreference.com/w/cpp/language/default_constructor:

>The implicitly-declared or defaulted (since C++11) default constructor for class T is defined as deleted if any of the following is true:
>
>    T has a non-[const-default-constructible](https://en.cppreference.com/w/cpp/language/default_initialization#Default_initialization_of_a_const_object) const member without a default member initializer (since C++11).

TL;DR non-`static` but `const` members of types with non-user provided default constructors won't be initialized by the defaulted default constructor so you have to default-initialize them explicitly by default member initializer.

Yeah, C++ is a nice language. 🙃

2022-05-26 08:00 UTC, kdudka requested changes
Thank you for working on this!  Overall it looks good.  A few minor changes suggested inline.

2022-05-26 08:00 UTC, kdudka commented on src/abstract-filter.cc
> -    fstr.close();
I do not think the call to `fstr.close()` is redundant.  If you remove it, the file will be unnecessarily kept open until `agent_->handleDef(def)` finishes.  There can be a big chain of decorators behind the call.

2022-05-26 08:00 UTC, kdudka commented on src/abstract-tree.hh
> +                const pt::ptree * /* root */) { }
I would remove this change.  The previous syntax feels more readable to me and did not cause any problems, as far as I know.

2022-05-26 08:00 UTC, kdudka commented on src/abstract-filter.hh
> +        unsigned thr_;
This change triggers a new warning:
```
src/abstract-filter.cc: In member function ‘virtual void EventPrunner::handleDef(const Defect&)’:
src/abstract-filter.cc:87:32: warning: comparison of integer expressions of different signedness: ‘const int’ and ‘unsigned int’ [-Wsign-compare]
   87 |         if (evt.verbosityLevel <= thr_)
      |             ~~~~~~~~~~~~~~~~~~~^~~~~~~
```

2022-05-26 08:10 UTC, kdudka commented on src/abstract-filter.hh
> +        unsigned thr_;
I think the proper fix would be this:
```diff
--- a/src/abstract-filter.hh
+++ b/src/abstract-filter.hh
@@ -61,7 +61,7 @@ class EventPrunner: public GenericAbstractFilter {
         int thr_;

     public:
-        EventPrunner(AbstractWriter *agent, unsigned thr):
+        EventPrunner(AbstractWriter *agent, int thr):
             GenericAbstractFilter(agent),
             thr_(thr)
         {
```

2022-05-26 10:09 UTC, lzaoral commented on src/abstract-filter.cc
> -    fstr.close();
I did not take into account this possibility. I'll revert this change.

2022-05-26 10:30 UTC, lzaoral commented on src/abstract-tree.hh
> +                const pt::ptree * /* root */) { }
Yes, it's only a cosmetic change but I think it makes the code more concise.

2022-05-26 12:04 UTC, lzaoral commented on src/abstract-filter.cc
> -    fstr.close();
Change dropped.

2022-05-26 12:06 UTC, lzaoral commented on src/abstract-tree.hh
> +                const pt::ptree * /* root */) { }
Commit dropped,

2022-05-26 12:07 UTC, lzaoral commented on src/abstract-filter.hh
> +        unsigned thr_;
Addressed in 1fd0a96.

2022-05-27 13:48 UTC, kdudka approved these changes

2022-05-27 13:48 UTC, kdudka commented on src/csparser.hh
> +        virtual EFileFormat inputFormat() const {
Should we spell this as `EFileFormat inputFormat() const override {` to be consistent with commit ecd971c4b951ed5b54db5ad5648b6f9f7d9c53ee?

2022-05-27 13:48 UTC, kdudka commented on src/gcc-parser.hh
> +        virtual EFileFormat inputFormat() const {
ditto

2022-05-27 13:48 UTC, kdudka commented on src/json-parser.hh
> +        virtual EFileFormat inputFormat() const {
ditto

2022-05-30 08:17 UTC, lzaoral commented on src/csparser.hh
> +        virtual EFileFormat inputFormat() const {
Definitely! I want to make this change as well but in a separate PR as this one is too big already (and focuses mainly on `src/abstrac-*` related changes). Is that ok with you?

2022-05-30 08:35 UTC, kdudka commented on src/csparser.hh
> +        virtual EFileFormat inputFormat() const {
This is new code you are introducing in this pull request.  I would prefer use the desired form since the beginning, rather than adding new code that we already plan to rework in a future pull request.  If it depends on other changes, the commit in question can be moved to the next pull request, to avoid unnecessary changes back and forth.

2022-05-30 09:10 UTC, lzaoral commented on src/csparser.hh
> +        virtual EFileFormat inputFormat() const {
Ok, let's drop this for now.

2022-05-30 10:22 UTC, lzaoral commented
Thanks for the reviews, @kdudka!

2022-05-30 10:22 UTC, merged

2022-05-30 11:08 UTC, kdudka commented
No problem.  Thank you for modernizing the code!