json-writer: replace invalid sequences in messages with �
csutils/csdiff pull request #46
Opened 2022-04-21 14:34 UTC by lzaoral

Fixes: #42

2022-04-21 15:20 UTC, kdudka requested changes
I like the solution but it needs to be extended to `sarifEncodeMsg()`, too:
```sh
$ echo $'\xb4' > x.c && echo 'x.c:1: warning: msg' | csgrep --mode=sarif -U1 | csgrep
-:71: error: invalid code sequence
```

2022-04-22 08:19 UTC, kdudka commented on src/json-writer.cc
> +    // � - REPLACEMENT CHARACTER U+FFFD
I would prefer not to have the special character directly in the source code.  Could we just write `0xEF 0xBF 0xBD` in the comment?

2022-04-25 12:44 UTC, kdudka commented
I am marking this as draft until we resolve the compatibility with EPEL buildroots.

2022-04-26 11:44 UTC, lzaoral commented on src/json-writer.cc
> +    // � - REPLACEMENT CHARACTER U+FFFD
Addressed in 620dc470d46908c64d3a5d14c78e015c71836aee.

2022-04-26 13:59 UTC, kdudka commented
Thanks!  I hit this difference in behavior while I was working on PR #48 yesterday.

2022-04-26 13:59 UTC, lzaoral commented
Thanks for the review, @kdudka! Merging.

2022-04-26 14:09 UTC, lzaoral commented
Thanks @praiskup! Addressed in f7e5c14fbbd0c0f48afdba50e4e7d427da48fce0. I'll merge this PR when it's green.

2022-04-26 14:35 UTC, merged