Modernize CMake
csutils/csdiff pull request #65
Opened 2022-07-28 14:38 UTC by lzaoral

2022-07-28 19:20 UTC, kdudka requested changes
Thank you for working on it!  Some minor comments inline...

2022-07-28 19:20 UTC, kdudka commented on src/CMakeLists.txt
> +    include(GNUInstallDirs)
There is already `include(GNUInstallDirs)` before `install(...)`.

2022-07-28 19:20 UTC, kdudka commented on src/CMakeLists.txt
>      endif()
This `endif()` should be removed by this commit and re-introduced by the commit that needs it.  Otherwise the checkout of commit 9d9fa6f478ef649f59a284d228bccc366b1ef9b2 fails to build with:
```
CMake Error at src/CMakeLists.txt:145 (endif):
  Flow control statements are not properly nested.
```

2022-07-28 19:25 UTC, lzaoral commented on src/CMakeLists.txt
> +    include(GNUInstallDirs)
Thanks! Originally, I wanted to move the man page generation to a separate file (like in cswrap) but the target in the in `add_custom_target` has to be defined in the same file (otherwise you get errors) and this is a leftover from that.

2022-07-29 10:05 UTC, lzaoral commented on src/CMakeLists.txt
> +    include(GNUInstallDirs)
Resolved in ce20660.

2022-07-29 10:05 UTC, lzaoral commented on src/CMakeLists.txt
>      endif()
Resolved in 4539356.

2022-07-29 10:27 UTC, lzaoral commented
This rebased version contains a lot of new changes, mainly in the Python related part.

2022-07-29 10:54 UTC, kdudka approved these changes
Given the fact that we migrated production Covscan hub off RHEL-7 yesterday, the support for Python 2 is not much important any more.  Nevertheless, thank you for putting the effort into this.  The new build system logic can be reused for migration to Python 4 later on ;-)

2022-07-29 11:25 UTC, merged

2022-07-29 11:26 UTC, lzaoral commented
Thank you for the review, @kdudka!