WIP: Support SARIF rule metadata
csutils/csdiff pull request #68
Opened 2022-08-01 15:01 UTC by lzaoral

This is a proof-of-concept at the moment.

Fixes #54.

2022-08-01 15:03 UTC, lzaoral commented
@jamacku, Can you please check that the version of `csgrep` from this branch creates correct help links for ShellCheck reports on GitHub? You can get the RPM from Packit. Thank you!

2022-08-01 15:31 UTC, jamacku commented
@lzaoral sure, I'll have a look. Thanks

2022-08-15 13:44 UTC, jamacku reviewed
Hmm, from what I saw help paragraphs are still missing. I'm not sure where could be a problem.

![image](https://user-images.githubusercontent.com/2879818/184646676-994d2153-6ad2-45f5-b966-87804188ca57.png)

2022-08-16 09:48 UTC, lzaoral commented
@jamacku, Could please try it again with the latest changes?  Note that this PR is just a proof-of-concept.  I'm not really happy with the current implementation.

2022-08-16 12:43 UTC, jamacku commented
@lzaoral It's unfortunate, but it still doesn't show a hint message in GitHub UI.

![Screenshot from 2022-08-16 14-41-42](https://user-images.githubusercontent.com/2879818/184882291-1632601f-a90b-42f1-9262-5b0a09dd3b4f.png)

2022-08-17 15:34 UTC, jamacku commented
@lzaoral I came across this repo with SARIF examples: https://github.com/microsoft/sarif-tutorials

It seems like a good source of information if it's not outdated.

https://github.com/microsoft/sarif-tutorials/blob/main/docs/2-Basics.md#rule-metadata

2022-08-18 10:43 UTC, lzaoral commented
@jamacku, could you try it once again, please?

I've added the `fullDescription` key to the rule objects.  This key is mandatory accroding to the SARIF 2.1 standard. [1]   Note, that I've just copied a event message to this key for testing purposes, it will contain description that's not really general, e.g. `"COMMIT_TO_IM appears unused. Verify it or export it."`.

[1] https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317838

2022-08-22 14:32 UTC, jamacku commented
@lzaoral It WORKS :partying_face: 
![Screenshot from 2022-08-22 16-29-50](https://user-images.githubusercontent.com/2879818/185946636-d7db4e7d-541e-4e28-a3e3-217d62ec30b3.png)

But I'm not sure if it displays a correct message.

2022-08-23 16:30 UTC, lzaoral commented
@jamacku, Could you try it once more, please?  This time with much cleaner and simpler code.  Thanks in advance!

2022-08-24 07:11 UTC, jamacku commented
@lzaoral Please see:

- https://github.com/jamacku/differential-shellcheck/pull/29

![Screenshot from 2022-08-24 09-05-55](https://user-images.githubusercontent.com/2879818/186353311-db415ee9-389b-41aa-9c8f-03580b4d5663.png)

It works great! :partying_face: I'm thinking if it would make sense to say something like:

```
Defect reference: https://github.com/koalaman/shellcheck/wiki/SC2086
```

Or maybe even try to take advantage of supported markdown templating and generate something like:

```markdown
Defect reference: [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086)
```

2022-08-26 12:49 UTC, jamacku commented
@lzaoral Works great :100: 

Markdown templating:

![Screenshot from 2022-08-26 14-45-58](https://user-images.githubusercontent.com/2879818/186906792-5b655ecb-911a-46bf-b6d4-528071bfc8f9.png)

Defect searching by rule:

![Screenshot from 2022-08-26 14-46-50](https://user-images.githubusercontent.com/2879818/186906800-bd6af1bb-23f2-4d63-933b-d461982b5b1a.png)

2022-09-14 14:32 UTC, lzaoral commented
This PR should be finally ready for a proper review. 🥳

2022-09-16 08:47 UTC, jamacku approved these changes
It works like a charm! LGTM :+1: 

- https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/117

2022-09-16 16:02 UTC, kdudka requested changes
Thank you for moving it forward!  Could we please extend the SARIF writer such that CWE IDs are preserved when available even for ShellCheck?  We have our own mapping of `SCNNNN` to `CWE-NNN` in csmock: https://github.com/csutils/csmock/blob/0d96eeabbc064f828c35fbea95ebd3616295b8b7/cwe-map.csv#L425  I would like to avoid loosing this data when we convert csmock's output to SARIF.

2022-09-19 12:29 UTC, lzaoral commented
Unfortunately, SARIF allows at most one rule per defect.  Will be something like this enough?
```json
"properties": {
    "cwe": [
        "CWE-248"
    ]
    "tags": [
        "ShellCheck"
    ]
}
```

2022-09-19 13:18 UTC, kdudka commented
SARIF's rule is `def.checker + ": " + keyEvt.event` in the current output of `csgrep --mode=sarif`.  So assigning at most one rule to each defect is fine and we do not need to change it.  On the other hand, we can assign many properties to each rule.  I am not sure about the help text.  If there is just one help text field for each rule, we can probably concatenate the text and provide both the links?

2022-09-19 13:22 UTC, lzaoral commented
Yes, concatenating the help texts is possible.

2023-02-07 12:57 UTC, lzaoral commented
I've updated the PR with changes addressing concerns raised in https://github.com/csutils/csdiff/pull/68#pullrequestreview-1110911556.

2023-02-09 09:09 UTC, kdudka approved these changes
Thanks for the update!  I think it works as expected now. 

The implementation could be optimized for future extensions.  I would create a structure `RuleProps` and a single map from `ruleId` to `RuleProps`, in order to make adding new properties in the future more straightforward.  But this can be refactored later on when we actually need it.

2023-02-09 12:07 UTC, jamacku requested changes
Hmm, it doesn't seem to work :crying_cat_face: 

Tested in:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/204
[Reported defect](https://github.com/redhat-plumbers-in-action/differential-shellcheck/security/code-scanning/208) is missing metadata:

![Screenshot from 2023-02-09 13-04-07](https://user-images.githubusercontent.com/2879818/217808064-8273c14b-feef-4701-8102-a44f2683e68a.png)

2023-02-09 12:18 UTC, jamacku approved these changes
When the defect was already detected before it won't have new metadata assigned to it, but when it is a fresh defect, it works as expected. It seems like a bug or implementation detail on the GitHub side.

![Screenshot from 2023-02-09 13-14-07](https://user-images.githubusercontent.com/2879818/217810570-5e2a7d59-8752-48b0-ab37-3a7ad9ad8637.png)

LGTM :muscle:

2023-02-09 13:01 UTC, merged