Port the project to C++11 - Part 2
csutils/csdiff pull request #72
Opened 2022-08-03 15:27 UTC by lzaoral

See commit messages.

2022-08-04 08:27 UTC, kdudka requested changes
Thanks!  Overall it looks good.  Two minor comments inline...

2022-08-04 08:27 UTC, kdudka commented on src/instream.cc
> +void InStream::handleError(const std::string& msg, const unsigned long line)
Please spell this as `const std::string &msg`.

2022-08-04 08:27 UTC, kdudka commented on src/instream.hh
> +        fileName(std::move(fileName_))
I fail to see how this would improve anything.  We save a copy of `std::string` in the constructor of `InFileException` at the cost of introducing a new copy of `std::string` at caller's side.  Let's not optimize something that has zero impact on performance.

2022-08-04 09:53 UTC, lzaoral commented on src/instream.hh
> +        fileName(std::move(fileName_))
I don't think I follow.  In the original code we always did one copy.  In the changed code, this is avoided in the case of temporaries (there will be moves but no unnecessary copies).

2022-08-04 10:56 UTC, kdudka commented on src/instream.hh
> +        fileName(std::move(fileName_))
The updated version does the copy here though (where the previous version only passed a reference): https://github.com/csutils/csdiff/blob/4b206d65e988f4225864b9894e9de06fa05a6eae/src/instream.cc#L34

2022-09-26 12:16 UTC, lzaoral commented on src/instream.cc
> +void InStream::handleError(const std::string& msg, const unsigned long line)
Addressed in 80ea97f and another reason why #86 should be implemented as soon as possible. ;)

2022-09-26 12:51 UTC, kdudka approved these changes
Looks good.  Thanks!

2022-09-26 12:53 UTC, lzaoral commented
Thanks for the review, @kdudka!

2022-09-26 12:53 UTC, merged