json-writer: print `level` key in SARIF output
csutils/csdiff pull request #81
Opened 2022-08-26 14:20 UTC by lzaoral

... so that users can easily filter results according to their severity.

Fixes: #80

2022-08-26 15:00 UTC, kdudka requested changes
Thank you for working on it!  Some minor issues inline...

2022-08-26 15:00 UTC, kdudka commented on src/json-writer.cc
> +        level = "error";
I do not like the fact that each level is typed twice (in the match and in the assignment).  This is prone to typos as the list will grow.  Could we rather implement it along these lines?
```cxx
    std::string level = event;                                                                
                                                                                              
    // cut the [...] suffix from event if present                                             
    size_t pos = event.find('[');
    if (std::string::npos != pos)
        level = event.substr(0U, pos);

    // go through events that denote warning level                                            
    for (const char *str : {"error", "warning", "note"}) {                                    
        if (str == level) {                                                                   
            // encode in the output if matched                                                
            result->put<std::string>("level", level);
            return;                                                                           
        }
    }   
```

2022-08-26 15:12 UTC, lzaoral commented on src/json-writer.cc
> +        level = "error";
That looks perfect, thanks!

2022-08-26 15:22 UTC, lzaoral commented on src/json-writer.cc
> +        level = "error";
Addressed in a3eac76.

2022-08-26 15:22 UTC, lzaoral commented on src/json-writer.cc
> +    std::string level = "warning";
Addressed in a3eac76.

2022-08-26 17:37 UTC, kdudka approved these changes
Thanks for the update!

2022-08-26 19:21 UTC, jamacku approved these changes
This is amazing, Thank you! :partying_face: 

![Screenshot from 2022-08-26 21-19-53](https://user-images.githubusercontent.com/2879818/186976670-0016a777-1717-4925-9995-79697c6ed958.png)

2022-08-27 06:45 UTC, merged

2022-09-20 17:43 UTC, lzaoral commented on src/json-writer.cc
> +static void sarifEncodeLevel(PTree *result, const std::string &event) {
Note to self: fix bracket formatting inconsistency in some future commit

2022-09-21 07:15 UTC, kdudka commented on src/json-writer.cc
> +static void sarifEncodeLevel(PTree *result, const std::string &event) {
We might consider using this one-liner in CI to catch this:
```
grep '^static .*) *{$' src/*
```

There is one more inconsistency in `abstarct-parser.cc`:
```
src/abstract-parser.cc:static inline std::unique_ptr<T> make_unique(InStream &input) {
src/json-writer.cc:static void sarifEncodeLevel(PTree *result, const std::string &event) {
```

2022-09-26 08:53 UTC, lzaoral commented on src/json-writer.cc
> +static void sarifEncodeLevel(PTree *result, const std::string &event) {
Using a custom `.clang-format` config to enforce code style is would be a better solution.
tracked in https://github.com/csutils/csdiff/issues/86.

2022-09-26 11:21 UTC, kdudka commented on src/json-writer.cc
> +static void sarifEncodeLevel(PTree *result, const std::string &event) {
That would mean more work than the proposed one-liner.  But if we have a volunteer to work on this, why not :-)

2022-09-26 11:31 UTC, lzaoral commented on src/json-writer.cc
> +static void sarifEncodeLevel(PTree *result, const std::string &event) {
It's not that hard, I've already done it few times.  Additionally, such config file can be then used in all of our projects.