json-parser-zap: support JSON format produced by OWASP ZAP
csutils/csdiff pull request #94
Opened 2022-11-09 16:21 UTC by kdudka

Fixes: https://github.com/csutils/csdiff/issues/90

2022-11-09 17:02 UTC, lzaoral requested changes
Thanks, @kdudka! Nitpicks inline.

2022-11-09 17:02 UTC, lzaoral commented on src/lib/parser-json-cov.cc
> +        evt.line        = valueOf<int>        (evtNode, "lineNumber", 0);
```suggestion
        evt.line        = valueOf<int>        (evtNode, "lineNumber");
```
Because `int() == 0`.

2022-11-09 17:02 UTC, lzaoral commented on src/lib/parser-json-zap.cc
> +    pDef->defectId = valueOf<int>(alertNode, "wascid", 0);
```suggestion
    pDef->cwe = valueOf<int>(alertNode, "cweid");
    pDef->imp = (1 < valueOf<int>(alertNode, "riskcode"));
    pDef->defectId = valueOf<int>(alertNode, "wascid");
```
Ditto.

2022-11-10 13:14 UTC, kdudka commented
@lzaoral Thanks for review!  I have updated the pull request per your suggestions.

2022-11-10 13:47 UTC, lzaoral approved these changes
Thanks, @kdudka!

2023-02-08 17:24 UTC, closed without merging